Repository codeStatesStudyProject/TravelPlanRepo, pull requests merged in 2022-09, with the labels that each got.

#2 1_Role User 수정
  src/main/java/travelplanrepo/account/entity/Role.java
  src/main/java/travelplanrepo/account/service/AccountService.java
Labels: test

#4 Sqush test
  src/main/java/travelplanrepo/TravelPlanRepoApplication.java
Labels: test

#6 #3. feat: add auditing
  .DS_Store
  .gitignore
  src/main/java/travelplanrepo/TravelPlanRepoApplication.java
  src/main/java/travelplanrepo/account/entity/Account.java
  src/main/resources/application.yml
Labels: feat

#9 [Docs] Issues Templet 추가
  .github/ISSUE_TEMPLATE/issue-template.md
Labels: docs

#11 [Docs] Pull requests Templet 추가
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/resources/application.yml
Labels: docs

#14 [Feat] File 관련 기능 구현
  .DS_Store
  .gitignore
  img/.DS_Store
  img/boardImg/.gitkeep
  img/boardImg/default.jpeg
  img/profileImg/.gitkeep
  img/profileImg/default.jpeg
  img/scheduleImg/.gitkeep
  img/scheduleImg/default.jpeg
  src/main/java/travelplanrepo/common/utill/File/File.java
  src/main/java/travelplanrepo/common/utill/File/FileController.java
  src/main/java/travelplanrepo/common/utill/File/FileProcessor.java
  src/main/resources/application.yml
Labels: feat

#18 [Feat] Board, Itinerary, Likes 생성
  src/main/java/travelplanrepo/board/entity/Board.java
  src/main/java/travelplanrepo/itinerary/entity/Itinerary.java
  src/main/java/travelplanrepo/likes/entity/Likes.java
Labels: feat

#20 [Feat] Board 등록 API 구현
  img/boardImg/f8f09818-f37d-41b9-86cc-5befb216ff18.jpeg
  img/scheduleImg/a25d6ff3-e02e-4c6e-9aa1-28e629721ae9.jpeg
  src/main/java/travelplanrepo/board/controller/BoardController.java
  src/main/java/travelplanrepo/board/dto/PostBoardDto.java
  src/main/java/travelplanrepo/board/entity/Board.java
  src/main/java/travelplanrepo/board/repository/BoardRepository.java
  src/main/java/travelplanrepo/board/service/BoardService.java
  src/main/java/travelplanrepo/itinerary/dto/PostItineraryDto.java
  src/main/java/travelplanrepo/itinerary/entity/Itinerary.java
  src/main/java/travelplanrepo/security/config/SecurityConfig.java
Labels: feat

#22 [Feat] Account SignUp API 구현
  src/main/java/travelplanrepo/account/controller/AccountController.java
  src/main/java/travelplanrepo/account/dto/PostAccountDto.java
  src/main/java/travelplanrepo/account/entity/Account.java
  src/main/java/travelplanrepo/account/entity/Gender.java
  src/main/java/travelplanrepo/account/service/AccountService.java
Labels: feat

#24 [Feat] Account 조회 기능 구현
  src/main/java/travelplanrepo/account/controller/AccountController.java
  src/main/java/travelplanrepo/account/dto/AccountRes.java
  src/main/java/travelplanrepo/account/service/AccountService.java
Labels: feat

#29 [Refactor] Board, Board 등록 API 수정 , Tag, BoardTag 생성
  build.gradle
  img/.DS_Store
  img/itineraryImg/.DS_Store
  img/itineraryImg/.gitkeep
  img/itineraryImg/default.jpeg
  src/main/java/travelplanrepo/domain/File/controller/FileController.java
  src/main/java/travelplanrepo/domain/File/service/FileService.java
  src/main/java/travelplanrepo/domain/Tag/dto/TagReq.java
  src/main/java/travelplanrepo/domain/Tag/entity/Tag.java
  src/main/java/travelplanrepo/domain/board/controller/BoardController.java
  src/main/java/travelplanrepo/domain/board/dto/PostBoardDto.java
  src/main/java/travelplanrepo/domain/board/entity/Board.java
  src/main/java/travelplanrepo/domain/board/entity/BoardTag.java
  src/main/java/travelplanrepo/domain/board/service/BoardService.java
  src/main/java/travelplanrepo/domain/itinerary/dto/PostItineraryDto.java
  src/main/java/travelplanrepo/domain/itinerary/entity/Itinerary.java
Labels: feat, refactor

#48 [Feat] Likes 생성,삭제 기능 구현
  src/main/java/travelplanrepo/domain/board/entity/Board.java
  src/main/java/travelplanrepo/domain/likes/controller/LikesController.java
  src/main/java/travelplanrepo/domain/likes/dto/PostLikesDto.java
  src/main/java/travelplanrepo/domain/likes/entity/Likes.java
  src/main/java/travelplanrepo/domain/likes/repository/LikesRepository.java
  src/main/java/travelplanrepo/domain/likes/service/LikesService.java
  src/main/java/travelplanrepo/global/common/auditing/BaseTime.java
Labels: feat, chore

#49 [Docs] Spring Rest Docs 환경설정, index.adoc 파일 생성
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/resources/static/docs/index.html
Labels: docs

#51 [Feat] Security 설정 변경 및, 예외처리 handler 구현
  build.gradle
  src/main/java/travelplanrepo/domain/account/entity/Account.java
  src/main/java/travelplanrepo/domain/account/entity/Role.java
  src/main/java/travelplanrepo/domain/account/repository/AccountRepository.java
  src/main/java/travelplanrepo/domain/account/service/AccountService.java
  src/main/java/travelplanrepo/global/exception/dto/ErrorResponse.java
  src/main/java/travelplanrepo/global/security/argumentresolver/LoginAccountIdArgumentResolver.java
  src/main/java/travelplanrepo/global/security/authentication/Principal.java
  src/main/java/travelplanrepo/global/security/authentication/UserAccount.java
  src/main/java/travelplanrepo/global/security/config/SecurityConfig.java
  src/main/java/travelplanrepo/global/security/controller/AuthController.java
  src/main/java/travelplanrepo/global/security/filter/AccountAccessDeniedHandler.java
  src/main/java/travelplanrepo/global/security/filter/AccountAuthenticationEntryPoint.java
  src/main/java/travelplanrepo/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/travelplanrepo/global/security/filter/JwtAuthorizationFilter.java
  src/main/java/travelplanrepo/global/security/properties/JwtProperties.java
  src/main/java/travelplanrepo/global/security/sevice/AuthService.java
  src/main/java/travelplanrepo/global/security/sevice/PrincipalDetailService.java
  src/main/java/travelplanrepo/global/security/utill/JwtProcessor.java
Labels: feat, refactor
